env:
  IMAGE_NODE: chain-testnet
  REGISTRY_HOSTNAME: multiversx

name: Build Docker image & push

on:
  pull_request:

jobs:
  build-docker-image:
    strategy:
      matrix:
        runs-on: [macos-13-xlarge]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build image
        run: |
          TAG_VERSION=${{ steps.get_version.outputs.VERSION }}
          cd ${GITHUB_WORKSPACE} && docker build -t "${REGISTRY_HOSTNAME}/${IMAGE_NODE}:${TAG_VERSION}" -f ./docker/Dockerfile .

